.github/workflows/lint-test.yml

I would like to be able to select on manual runs the script to run.

lets try to add a param

---

test/parallel/xyk-pallet.sudo.security.test.ts

@iStrike7 , @stanieltron ,
@gleb-urvanov  ask me to have a second round of reviews. We may have some scenarios or something else :S
Thanks!

security tests for sudo only operations

---

package.json
test/parallel/xyk-pallet.API.accuracy.tx.fees.test.ts
test/parallel/xyk-pallet.API.burnLiquidity.test.ts
test/parallel/xyk-pallet.API.buyAsset.test.ts
test/parallel/xyk-pallet.API.mintLiquidity.error.test.ts
test/parallel/xyk-pallet.API.mintLiquidity.test.ts
test/parallel/xyk-pallet.API.sellAsset.test.ts
test/parallel/xyk-pallet.API.treasury.no.connected.mangata.test.ts
test/parallel/xyk-pallet.asset.buy.test.ts
test/parallel/xyk-pallet.sudo.test.ts
test/sequential/xyk-SDK.nonce.test.ts
test/sequential/xyk-pallet.API.treasury.connected.mangata.test.ts
test/sequential/xyk-pallet.test.ts
test/ui/ui-main.ETH.test.ts
test/ui/ui-main.test.ts
utils/api.ts
utils/tx.ts
utils/txHandler.ts
utils/utils.ts
yarn.lock

0.2.1
Reduced the scope, the PR is big enough. 
+ Add SDK version 0.2.1
+ Use Create Pool from SDK

upgrade to new sdk version

---

.github/workflows/recurrent-checks.yml
test/ci/xyk-ci.validate.assetInfo.test.ts
utils/User.ts

Added mKSM, mBTC, and mUSD tokens in checking AssetInfo.

Feature/fix GitHub action tests for ci checks

---

test/parallel/xyk-pallet.API.buyAsset.test.ts
test/parallel/xyk-pallet.API.sellAsset.test.ts

there are still some randomly failing tests cases due to "mapping issue" tests affexted by [MGX-251] has been fixed
https://github.com/mangata-finance/mangata-node/pull/378/checks?check_run_id=10208012221
https://github.com/mangata-finance/mangata-node/actions/runs/3739785663/jobs/6348262378
[MGX-251]: https://mangatafinance.atlassian.net/browse/MGX-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MGX-251] - Default transactional alignment

---

.github/workflows/lint-test.yml
test/parallel/xyk-pallet.API.buyAsset.test.ts
test/parallel/xyk-pallet.asset.register.test.ts
test/sequential/xyk-SDK.nonce.test.ts
test/sequential/xyk-pallet.API.stacking.lock.test.ts
test/sequential/xyk-pallet.asset.bootstrap.register.test.ts

Feature/update test version 0.26.2

---

.github/workflows/ui-test.yml

Update develop address for FE tests in ui-test.yml

Update develop address for FE tests in ui-test.yml

---

utils/frontend/pages/Mangata.ts

fix for flaky FE test test/ci/ui-ci.validate.ui.test.ts

fix for flaky FE test

---

package.json
test/parallel/feeLock.API.feePayment.parallel.test.ts
test/parallel/feeLock.API.swapValueThresholds.test.ts
test/parallel/feeLock.API.unlocking.test.ts
test/parallel/xyk-pallet.API.accuracy.tx.fees.test.ts
test/parallel/xyk-pallet.API.fees.tripleTokens.test.ts
test/parallel/xyk-pallet.API.pool.test.ts
test/parallel/xyk-pallet.MPL.test.ts
test/parallel/xyk-pallet.asset.buy.test.ts
test/sequential/feeLock.API.config.test.ts
test/sequential/feeLock.API.feePayment.sequential.test.ts
test/sequential/xyk-pallet.API.accuracy.MGA.fees.test.ts
test/sequential/xyk-pallet.API.fees.v2.test.ts
test/sequential/xyk-pallet.API.stacking.lock.test.ts
test/sequential/xyk-pallet.API.treasury.v2.test.ts
utils/Assets.ts
utils/User.ts
utils/feeLockHelper.ts
utils/globalSetup.js
utils/setup.ts
utils/setupJest.ts
utils/utils.ts
yarn.lock

Adapt tests to new gasless enabled

---

.github/workflows/microapps-ui-test.yml
package.json
test/microapps-ui/microapps-ui-main.extensions.test.ts
utils/frontend/microapps-pages/Sidebar.ts

- Basic smoke test for new FE app (microapps)
- Test will be used in deployment to dev workflow as verification
- Tests for old app are still in repo, created new script and subfolders 
- microapps-ui to gather new app tests
- microapps-pages to gather related utils
- new test-microapps-ui script to run tests with --group=microapps-ui
- Main app div locator is now in Sidebar.ts - ideally for smoke test I want to see all elements visible but right now there is not much to locate so this is temporary

FE: Microapps (new app) smoke test and script

---

test/microapps-ui/microapps-ui-main.extensions.test.ts
test/microapps-ui/microapps-ui-main.smoke.test.ts
utils/frontend/microapps-pages/Main.ts
utils/frontend/microapps-pages/WalletConnectModal.ts
utils/frontend/microapps-pages/WalletWrapper.ts
utils/frontend/utils/Driver.ts
utils/frontend/utils/Handlers.ts
utils/frontend/utils/Helper.ts

- Added Polkadot.js wallet connecting test
- Added component/page handlers like WalletWrapper (new) and WalletConnectModal (similar to old one)
- Removed metamaskExtension setup, but soon Talisman/Enkrypt/Subwallet will be added

Microapps polkadotjs wallet test

---

test/microapps-ui/microapps-ui-main.extensions.test.ts
utils/frontend/utils/Driver.ts

Few things to optimise tests:
- Added headless flag to executions
- Disable dev shm flag - just to be safe due to issues like: "The /dev/shm partition is too small in certain VM environments, causing Chrome to fail or crash"
- Added talisman extension

E2E PR flow updates

---

utils/frontend/utils/Driver.ts

Turns out headless flag messes up talisman extension handling

Fix e2e pr checks microapps

---

.github/workflows/microapps-ui-test.yml
.github/workflows/ui-test.yml
package.json
test/ui/ui-main.poolsLiquidity.addRemove.test.ts
utils/frontend/pages/BurnLiquidityModal.ts
utils/frontend/pages/Pool.ts
utils/frontend/pages/Sidebar.ts
utils/frontend/pages/Talisman.ts
utils/frontend/utils/Driver.ts

Tests are passing:
https://mangata-finance.testmo.net/automation/runs/view/256
- Upgraded chrome driver and selenoid chrome to 112.0.0
- Added Liquidity adding and removing tests
- Liquidity adding test ends up on toggling & validating pool tab  - as we have already providing pool action tested in separate test
- Minor cleanups and fixes

adding liquidity add/remove tests

---

package.json
test/microapps-ui/microapps-ui-main.extensions.test.ts
test/ui/ui-main.extensions.test.ts
test/ui/ui-main.pools.test.ts
test/ui/ui-main.poolsLiquidity.addRemove.test.ts
test/ui/ui-main.swapping.test.ts

- Introducing specific command in package.json for microapps PR tests test-microapps-pr
- Temporary excluding Talisman test in PR microapps checks via not-so-pretty testNamePattern that does not collide with groups
- Introducing retries for current app UI tests for stability

Fe microapps pr command & fixes

---

package.json
test/ui/ui-main.extensions.test.ts
test/ui/ui-main.pools.test.ts
test/ui/ui-main.poolsLiquidity.addRemove.test.ts
test/ui/ui-main.swapping.test.ts
utils/frontend/microapps-pages/Main.ts
utils/frontend/utils/Helper.ts

- Adjusting test groups so they are clearly different (uiMain and uiXCM, previously having just ui)
- Adjusting isToastDisplayed in microapps tests

FE tests fixes

---

test/ui-xcm/ui-main.KSM.deposit.test.ts
test/xcm/__snapshots__/kusama.transfer.test.ts.snap
test/xcm/kusama.transfer.test.ts

Updates to make chops xcm tests work, according to this:
https://github.com/AcalaNetwork/chopsticks/pull/302/files#diff-5e79501b9990ae4dd02baeee8653f9ffa8c0551fef71fd002030411241666464R13
- xcm tests are passing
- xcm UI tests are passing

Xcm update kusama config

---

test/ui/ui-main.poolsLiquidity.addRemove.test.ts
utils/frontend/pages/Sidebar.ts

- Better waits 
- Simplifying session management in multiple-test suite add/remove LP tests

stabilising add/remove LP tests

---

.github/workflows/microapps-ui-test.yml
test/microapps-ui/microapps-ui-main.extensions.test.ts
test/microapps-ui/microapps-ui-main.smoke.test.ts
test/microapps-ui/microapps-ui-main.swap.test.ts
utils/frontend/microapps-pages/Main.ts
utils/frontend/microapps-pages/Swap.ts
utils/frontend/microapps-utils/Handlers.ts
utils/frontend/utils/Helper.ts

- added microapps swap basic tests
- added helpers and access methods for microapps swap
- refactors to make tests shorter
- added mnemonic to workflow for rococo test user, for now microapps tests are only rococo-based

Microapps swap tests

---

.github/workflows/microapps-ui-test.yml
test/microapps-ui/microapps-ui-main.smoke.test.ts
test/microapps-ui/microapps-ui-main.swap.test.ts
utils/frontend/microapps-pages/Swap.ts

Expanding swap view tests:
- tests do not perform action, just verify UI
Test list:
- Swap fee lock - less than 10k MGX
- Swap free - more than 10k MGX
- Swap alert - not enough MGX to do transaction
- Swap alert - not enough MGX to lock
- Switch transaction tokens and values
Also cleaning-up microapps workflow

Microapps - more swap test scenarios

---

.github/workflows/ui-xcm-tests.yml

PR removing custom fixed sdk used in xcm chops tests - its now passing with latest one. Also adding new moonriver env variable.

UI xcm remove custom sdk

---

.github/workflows/ui-prod-smoke-test.yml
test/ui/ui-prod.smoke.test.ts
utils/frontend/pages/Sidebar.ts
utils/frontend/pages/Swap.ts

Set of simple prod smoke tests - these do no actions but verify app starts and behaves correctly:
- user can connect wallet
- user can see sidebar elements, tokens, token amounts, liq pools
- user can input swap values and swap is being validated
- user can open deposit modal and inputs are being validated

Dex prod checks tests & workflow

---

test/parallel/xyk-pallet.API.pool.deactivated.test.ts

https://mangatafinance.atlassian.net/browse/MGX-531

Test for MGX-531. Users can iteract with a disabled pool

---

test/parallel/assetRegistry.getTradeable.rpc.test.ts
test/parallel/sdk.API.getInfo.test.ts

https://mangata-finance.testmo.net/runs/view/61?group_id=1364
https://mangatafinance.atlassian.net/browse/MGX-524

add test for getTradeable tokens + add a few comments on existing ones

---

test/microapps-ui-xcm/microapps-ui-main.liq.pools.test.ts
utils/frontend/microapps-pages/LiqPoolDetails.ts
utils/frontend/microapps-pages/LiqPools.ts
utils/frontend/microapps-pages/Main.ts
utils/frontend/microapps-pages/Sidebar.ts
utils/frontend/microapps-utils/Handlers.ts

- ver1 of pools list & details tests
- access methods for liq pools and details
- fix for slow tests - tests are waiting to skip beta info for too long, and we dont have such info anymore on connected wallet

E2e pools list test and fixes

---

test/microapps-ui-xcm/microapps-ui-main.liq.pools.test.ts
utils/frontend/microapps-pages/LiqPoolDetails.ts
utils/frontend/microapps-pages/LiqPools.ts
utils/frontend/utils/Helper.ts

More test cases for microapps liq pools list:
- adding liquidity
- input fields validations
- tab / filrtering
Successful run:

Adding microapps pools list test scenarios

---

test/microapps-ui-xcm/microapps-ui-main.tokens.test.ts
utils/frontend/microapps-pages/TokenDetails.ts
utils/frontend/microapps-pages/Tokens.ts

Adding tests to token details page, checking token rows, filtering and token details page.

Microapps - token details tests

---

.github/workflows/ui-xcm-tests.yml
test/microapps-ui-xcm/microapps-ui-main.deposit.BNC.test.ts
test/microapps-ui-xcm/microapps-ui-main.deposit.IMBU.test.ts
test/microapps-ui-xcm/microapps-ui-main.deposit.KSM.test.ts
test/microapps-ui-xcm/microapps-ui-main.deposit.TUR.test.ts
utils/stashServiceMockSingleton.ts

feat: xcm tests for microapps

---

test/rollup-test/rollup-main.metamask.test.ts
utils/frontend/microapps-pages/StakingPage.ts
utils/frontend/pages/DepositModal.ts
utils/frontend/pages/MetaMask.ts
utils/frontend/pages/Sidebar.ts
utils/frontend/utils/Driver.ts
utils/frontend/utils/Helper.ts

- utils to import metamask account (a lot of clicking)
- metamask extension crx added
- metamask extension added to Driver
- placeholder test for wallet connection
- cleanup of older metamask imports
Video of current meta onboarding process:
https://github.com/mangata-finance/mangata-e2e/assets/112616777/6f2c4f97-2e34-4a89-afbb-412d46601d0c

FEX Metamask utils

---

Readme.md

There were some mistakes in the Readme.md file. So, I thought it would be nice to fix them for the developers who will check the repo in the future.

Update / Fix Readme.md

---

test/microapps-ui-xcm/microapps-ui-main.accounts.test.ts
test/microapps-ui-xcm/microapps-ui-main.liq.pools.test.ts
test/microapps-ui-xcm/microapps-ui-main.swap.test.ts
test/microapps-ui-xcm/microapps-ui-main.withdraw.test.ts
utils/frontend/microapps-pages/LiqPoolDetails.ts
utils/frontend/microapps-pages/LiqPools.ts
utils/frontend/microapps-pages/NotificationToast.ts
utils/frontend/microapps-utils/Handlers.ts

Changes in tests to comply with new non-blocking notification toasts

Feat/mgx 843 non blocking tx UI

---

utils/calculate_rewards_all_response.json
utils/calculate_rewards_amount_response.json
utils/wsMock.cjs

adding mocks for rewards to ws proxy

add more ws mocks for rewards

---

package.json
test/rollup-test/rollup-main.metamask.test.ts
test/rollup-test/rollup-main.withdraw.test.ts
utils/frontend/pages/MetaMask.ts
utils/frontend/rollup-pages/NotificationToast.ts
utils/frontend/rollup-pages/WithdrawModal.ts
utils/frontend/rollup-utils/Handlers.ts

Adding tests for withdrawal - green workflow here:
https://github.com/mangata-finance/mangata-e2e/actions/runs/9158474736

FE rollup withdraw test

---

utils/frontend/pages/MetaMask.ts

Metamask added somenew popup to handle

Update prod e2e

---

test/rollup-test/rollup-prod.deposit.test.ts
test/rollup-test/rollup-prod.withdraw.test.ts
utils/frontend/rollup-pages/WalletWrapper.ts
utils/frontend/rollup-pages/WithdrawModal.ts
utils/frontend/rollup-utils/DepositModal.ts
utils/frontend/rollup-utils/Handlers.ts

locators for e2e tests, updated deposit and withdraw flow along with post release changes

E2E FE update prod transfer tests

---

.github/workflows/gasp-prod-smoke-test.yml
utils/frontend/rollup-pages/WalletWrapper.ts
utils/frontend/rollup-utils/Handlers.ts
utils/frontend/utils/Helper.ts

New locators to adjust tests for new ui https://mangatafinance.atlassian.net/browse/MGX-1401
And temp switch for prod tests to use specific repo commit to not break tests until we have new FE release:
`- uses: actions/checkout@v3
with:
ref: 69ea990afdc7b1d12ffd3324b3b09e88aaa31464
`

FE new layout adjusted locators

---

test/microapps-prod/microapps-prod-main.pools.test.ts
test/microapps-prod/microapps-prod-main.staking.test.ts

Skip on flaky test and retries - connected to https://mangatafinance.atlassian.net/browse/MGX-1395

FE Dex app retries on staking tests

---

.github/workflows/microapps-ui-test.yml
test/rollup-test/rollup-main.deposit.test.ts
test/rollup-test/rollup-main.my-positions.test.ts
test/rollup-test/rollup-main.swap.test.ts
test/rollup-test/rollup-main.withdraw.test.ts
utils/frontend/pages/MetaMask.ts
utils/frontend/rollup-pages/Main.ts
utils/frontend/rollup-pages/WithdrawModal.ts
utils/frontend/rollup-utils/DepositModal.ts
utils/frontend/rollup-utils/Handlers.ts
utils/frontend/utils/Helper.ts

Adding transaction rejection  cases

Gasp fe more rejection tests

---

.github/workflows/gasp-prod-smoke-test.yml
test/rollup-test/rollup-prod.deposit.test.ts
test/rollup-test/rollup-prod.withdraw.test.ts
utils/frontend/pages/MetaMask.ts
utils/frontend/rollup-utils/Handlers.ts

Updated for prod checks post-release

Fe prod checks update

---

.github/workflows/gasp-prod-smoke-test.yml

Setting custom branch until we release FE changes to prod

Set FE prod tests to custom branch

---

.github/workflows/gasp-prod-smoke-test.yml

Update gasp-prod-smoke-test.yml

Testmo reporting for FE prod tests

---

.github/workflows/ui-prod-smoke-test.yml

FE disable mangata prod tests
